# Generated by Django 5.1 on 2024-09-04 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moodentry',
            name='sadness_level',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
